module.exports = {
  "status": 200,
  "data": {
    "venue": {
      "venueId": 396,
      "venueName": "Madison Square Garden",
      "venueOverview": "Madison Square Garden is a venue in New York that is usually used for Basketball",
      "venueAddress": "4 Pennsylvania Plaza",
      "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
      "coOrdinates": {
        "latitude": 40.750504,
        "longitude": -73.99343899999997
      },
      "city": {
        "cityId": 9,
        "cityName": "New York",
        "cityOverview": null,
        "country": {
          "countryId": "US",
          "countryName": "United States"
        },
        "imageURL": "https://graphics.sportswhereiam.com/city/9.jpg"
      }
    },
    "events": [
      {
        "eventId": 151901,
        "headline": "The Cowboy Channel: Rodeo New York",
        "eventName": "The Cowboy Channel: Rodeo New York",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "Rodeo",
        "league": {
          "leagueId": 1000,
          "leagueName": "Rodeo",
          "leagueAbbreviation": "Rodeo",
          "sport": {
            "sportID": 1000,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportName": "Rodeo"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 1000,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
        "venueId": 396,
        "sportName": "Rodeo",
        "dateTime": 3170448000000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=151901",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2070-06-20T00:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 151902,
        "headline": "The Cowboy Channel: Rodeo New York",
        "eventName": "The Cowboy Channel: Rodeo New York",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "Rodeo",
        "league": {
          "leagueId": 1000,
          "leagueName": "Rodeo",
          "leagueAbbreviation": "Rodeo",
          "sport": {
            "sportID": 1000,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportName": "Rodeo"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 1000,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
        "venueId": 396,
        "sportName": "Rodeo",
        "dateTime": 3170448000000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=151902",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2070-06-20T00:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 151903,
        "headline": "The Cowboy Channel: Rodeo New York",
        "eventName": "The Cowboy Channel: Rodeo New York",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "Rodeo",
        "league": {
          "leagueId": 1000,
          "leagueName": "Rodeo",
          "leagueAbbreviation": "Rodeo",
          "sport": {
            "sportID": 1000,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportName": "Rodeo"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 1000,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
        "venueId": 396,
        "sportName": "Rodeo",
        "dateTime": 3170361600000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=151903",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2070-06-19T00:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 151904,
        "headline": "The Cowboy Channel: Rodeo New York",
        "eventName": "The Cowboy Channel: Rodeo New York",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "Rodeo",
        "league": {
          "leagueId": 1000,
          "leagueName": "Rodeo",
          "leagueAbbreviation": "Rodeo",
          "sport": {
            "sportID": 1000,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportName": "Rodeo"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 1000,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
        "venueId": 396,
        "sportName": "Rodeo",
        "dateTime": 3170534400000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=151904",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2070-06-21T00:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 168469,
        "headline": "WWE: Live - Road to Wrestlemania",
        "eventName": "WWE: Live - Road to Wrestlemania",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "WWE",
        "league": {
          "leagueId": 911,
          "leagueName": "WWE",
          "leagueAbbreviation": "WWE",
          "sport": {
            "sportID": 910,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
            "sportName": "Wrestling"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 910,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_SWiAM_S_Alt.png",
        "venueId": 396,
        "sportName": "Wrestling",
        "dateTime": 3171052800000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=168469",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2070-06-27T00:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 175009,
        "headline": "Empire Classic - Friday",
        "eventName": "Empire Classic - Friday",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "NCAABK",
        "league": {
          "leagueId": 100,
          "leagueName": "College Basketball",
          "leagueAbbreviation": "NCAABK",
          "sport": {
            "sportID": 100,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
            "sportName": "Basketball"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 100,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
        "venueId": 396,
        "sportName": "Basketball",
        "dateTime": 1605891600000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=175009",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2020-11-20T17:00",
        "niceWhen": null,
        "isFuture": null
      },
      {
        "eventId": 175010,
        "headline": "Empire Classic - Thursday",
        "eventName": "Empire Classic - Thursday",
        "eventImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "venueImage": "https://graphics.sportswhereiam.com/venue/396.jpg",
        "leagueImage": "https://graphics.sportswhereiam.com/league/default_league.jpg",
        "leagueId": "NCAABK",
        "league": {
          "leagueId": 100,
          "leagueName": "College Basketball",
          "leagueAbbreviation": "NCAABK",
          "sport": {
            "sportID": 100,
            "sportIconURL": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
            "sportIconURLV4": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
            "sportName": "Basketball"
          },
          "leagueDescription": null,
          "photoURL": "https://graphics.sportswhereiam.com/league/default_league.jpg",
          "cardImageURL": "https://graphics.sportswhereiam.com/league/default_league_card.jpg"
        },
        "sportId": 100,
        "sportIcon": "https://api.sportswhereiam.com/swiam-api/imgs/sports/png_basketball.png",
        "venueId": 396,
        "sportName": "Basketball",
        "dateTime": 1605812400000,
        "priceFrom": null,
        "venueWordpressId": null,
        "buyTicketsURL": "/todo/event=175010",
        "teamA": null,
        "teamB": null,
        "abbrev": null,
        "cityId": 9,
        "timelineItemType": null,
        "dateTimeStamp": "2020-11-19T19:00",
        "niceWhen": null,
        "isFuture": null
      }
    ]
  },
  "errorCode": null,
  "errorMessage": null
};
