swiam-gql:
  build: .
  env_file:
    - .env.staging
  volumes:
    - ./:/usr/src/app
  ports:
    - "4000:4000"
    - "5000:5000"
  environment:
    - NODE_ENV="staging"
    - BASE_API=https://api.sportswhereiam.com/swiam-api
    - BASE_API_V2=https://apidev2.sportswhereiam.com/openapi
    - PORT=5000
    - TIME_OUT=3000
    - CITY_ROUTE=/v3i/cities
    - BASE_GQL_URL=http://localhost

