module.exports = {
  data: {
    id: 100,
    leagueId: 530,
    leagueAbbreviation: 'NCAAFB',
    leagueName: 'College Football',
    sport: {
      sportID: 500,
      sportIconURL:
        'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
      sportIconURLV4:
        'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
      sportName: 'Football',
    },
    leagueDescription:
      'College Football is a Football competition held in Canada and United States',
    photoURL:
      'https://swiam-cms.s3-ap-southeast-2.amazonaws.com/league/default_league.jpg',
    cardImageURL:
      'https://swiam-cms.s3-ap-southeast-2.amazonaws.com/league/default_league_card.jpg',
    events: [
      {
        eventId: 163002,
        headline: 'Penn State Nittany Lions vs. Ohio State Buckeyes',
        eventName: 'Penn State Nittany Lions vs. Ohio State Buckeyes',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1603497600000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163002',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-10-24T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163003,
        headline: 'Penn State Nittany Lions vs. Iowa Hawkeyes',
        eventName: 'Penn State Nittany Lions vs. Iowa Hawkeyes',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1602892800000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163003',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-10-17T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163004,
        headline: 'Penn State Nittany Lions vs. Maryland Terrapins',
        eventName: 'Penn State Nittany Lions vs. Maryland Terrapins',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1605916800000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163004',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-11-21T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163005,
        headline: 'Penn State Nittany Lions vs. Kent State Golden Flashes',
        eventName: 'Penn State Nittany Lions vs. Kent State Golden Flashes',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1599264000000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163005',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-09-05T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163006,
        headline: 'Penn State Nittany Lions vs. Northwestern Wildcats',
        eventName: 'Penn State Nittany Lions vs. Northwestern Wildcats',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1601078400000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163006',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-09-26T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163007,
        headline: 'Penn State Nittany Lions vs. San Jose State Spartans',
        eventName: 'Penn State Nittany Lions vs. San Jose State Spartans',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1600473600000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163007',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-09-19T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 163008,
        headline: 'Penn State Nittany Lions vs. Michigan State Spartans',
        eventName: 'Penn State Nittany Lions vs. Michigan State Spartans',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 612,
        sportName: 'Football',
        dateTime: 1605312000000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=163008',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 16,
        timelineItemType: null,
        dateTimeStamp: '2020-11-14T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 164684,
        headline: 'LSU Tigers vs. UTSA Roadrunners',
        eventName: 'LSU Tigers vs. UTSA Roadrunners',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 891,
        sportName: 'Football',
        dateTime: 1599264000000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=164684',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 35,
        timelineItemType: null,
        dateTimeStamp: '2020-09-05T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 164685,
        headline: 'LSU Tigers vs. Texas Longhorns',
        eventName: 'LSU Tigers vs. Texas Longhorns',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 891,
        sportName: 'Football',
        dateTime: 1599868800000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=164685',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 35,
        timelineItemType: null,
        dateTimeStamp: '2020-09-12T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 164686,
        headline: 'LSU Tigers vs. South Carolina Gamecocks',
        eventName: 'LSU Tigers vs. South Carolina Gamecocks',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 891,
        sportName: 'Football',
        dateTime: 1605312000000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=164686',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 35,
        timelineItemType: null,
        dateTimeStamp: '2020-11-14T00:00',
        niceWhen: null,
        isFuture: null,
      },
      {
        eventId: 164687,
        headline: 'LSU Tigers vs. Mississippi Rebels',
        eventName: 'LSU Tigers vs. Mississippi Rebels',
        sportid: 500,
        sportIcon:
          'https://api.sportswhereiam.com/swiam-api/imgs/sports/png_nfl.png',
        venueid: 891,
        sportName: 'Football',
        dateTime: 1601078400000,
        priceFrom: null,
        venueWordpressID: null,
        buyTicketsURL: '/todo/event=164687',
        teamA: null,
        teamB: null,
        abbrev: null,
        cityid: 35,
        timelineItemType: null,
        dateTimeStamp: '2020-09-26T00:00',
        niceWhen: null,
        isFuture: null,
      },
    ],
  },
};
