defaults: &defaults
  working_directory: ~/app/
  docker:
    - image: circleci/node:10.16.3
      environment:
        BASE_GQL_URL: "http://localhost"
        BASE_API: "https://apidev.sportswhereiam.com/swiam-api"
        BASE_API_V2: "https://apidev2.sportswhereiam.com/openapi"

uat-envs: &uat-envs
  environment:
    BASE_GQL_URL: "http://localhost"
    BASE_API: "https://apidev.sportswhereiam.com/swiam-api"
    BASE_API_V2: "https://apidev2.sportswhereiam.com/openapi"

version: 2.1
orbs:
  node: circleci/node@1.0.1
  gke: circleci/gcp-gke@1.0.3
  gcr: circleci/gcp-gcr@0.6.1
jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Setup common environment variables
          command: |
            echo 'export APP_ENV="staging"' >> $BASH_ENV
            echo 'export BASE_API="https://apidev.sportswhereiam.com/swiam-api" >> $BASH_ENV
            echo 'export BASE_API_V2="https://apidev2.sportswhereiam.com/openapi" >> $BASH_ENV
            echo 'export BASE_GQL_URL="http://localhost" export PORT="5000"' >> $BASH_ENV
            echo 'export PORT="5000"' >> $BASH_ENV
      - run: NODE_ENV=development yarn
      - run:
          name: Tests
          command: yarn test --maxWorkers 2
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules/
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          extra_build_args: "BASE_API='https://apidev.sportswhereiam.com/swiam-api' BASE_API_V2='https://apidev2.sportswhereiam.com/openapi' BASE_GQL_URL='http://localhost"
          image: swiam-gql
          tag: $CIRCLE_SHA1 #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: swiam-gql
          tag: $CIRCLE_SHA1 #Change version number e.g to 'v3' when updating application

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - gke/install
      - gke/update-kubeconfig-with-credentials:
          cluster: swiam-cluster
          perform-login: true
      - gke/rollout-image:
          cluster: swiam-cluster
          deployment: swiam-gql
          container: swiam-gql
          image: gcr.io/swiam-274409/swiam-gql # change version when updating
          tag: $CIRCLE_SHA1
workflows:
  build_update_deploy:
    jobs:
      - build-and-test
      - Build-Push-Image-Docker:
          requires:
            - build-and-test
      - deploy:
          requires:
            - Build-Push-Image-Docker
          filters:
            branches:
              only:
                - develop

