module.exports = {
  data: [
    {
      id: 1,
      title: 'Intro',
      imageAspect: null,
      imageURL: 'https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      interestTagging: {
        homepage: null,
        cityId: null,
        venueId: null,
        teamId: null,
        leagueId: 1,
      },
      videoID: 1,
      videoURL: 'https://www.youtube.com/watch?v=llOd5ixWD-0',
      objectType: 'VIDEO',
      videoType: 'YOUTUBE',
    },
    {
      id: 3,
      title: 'Sarah',
      imageAspect: null,
      imageURL: 'https://images.pexels.com/photos/221210/pexels-photo-221210.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      interestTagging: {
        homepage: null,
        cityId: null,
        venueId: null,
        teamId: null,
        leagueId: 1,
      },
      videoID: 2,
      videoURL: 'https://www.youtube.com/watch?v=9pW-jOD56Pk',
      objectType: 'VIDEO',
      videoType: 'YOUTUBE',
    },
    {
      id: 4,
      title: 'Sarah',
      imageAspect: null,
      imageURL: 'https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500://images.pexels.com/photos/221210/pexels-photo-221210.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      interestTagging: {
        homepage: null,
        cityId: null,
        venueId: null,
        teamId: null,
        leagueId: 1,
      },
      videoID: 2,
      videoURL: 'https://www.youtube.com/watch?v=9pW-jOD56Pk',
      objectType: 'VIDEO',
      videoType: 'YOUTUBE',
    },
    {
      id: 5,
      title: 'Sarah',
      imageAspect: null,
      imageURL: 'https://images.pexels.com/photos/221210/pexels-photo-221210.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      interestTagging: {
        homepage: null,
        cityId: null,
        venueId: null,
        teamId: null,
        leagueId: 1,
      },
      videoID: 2,
      videoURL: 'https://www.youtube.com/watch?v=9pW-jOD56Pk',
      objectType: 'VIDEO',
      videoType: 'YOUTUBE',
    },
    {
      id: 6,
      title: 'Sarah',
      imageAspect: null,
      imageURL: 'https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      interestTagging: {
        homepage: null,
        cityId: null,
        venueId: null,
        teamId: null,
        leagueId: 1,
      },
      videoID: 2,
      videoURL: 'https://www.youtube.com/watch?v=9pW-jOD56Pk',
      objectType: 'VIDEO',
      videoType: 'YOUTUBE',
    },
  ],
};
