apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: swiam-gql
  labels:
    app: graphql-service-swiam
spec:
  selector:
    matchLabels:
      app: swiam-gql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: swiam-gql
        tier: backend
    spec:
      containers:
        - image: gcr.io/swiam-274409/swiam-gql:0.1.0
          name: swiam-gql
          ports:
            - containerPort: 5000
              name: swiam-gql

