module.exports = {
  data: [
    {
      resultID: 1,
      resultText: 'New York City',
      type: 'CITY',
      subType: '',
      date: '',
      venue: '',
    },
    {
      resultID: 2,
      resultText: 'Newark',
      type: 'CITY',
      subType: '',
      date: '',
      venue: '',
    },
    {
      resultID: 3,
      resultText: 'New Orleans',
      type: 'CITY',
      subType: '',
      date: '',
      venue: '',
    },
    {
      resultID: 3.5,
      resultText: 'New Jersey',
      type: 'CITY',
      subType: '',
      date: '',
      venue: '',
    },
    {
      resultID: 4,
      resultText: 'New York Yankees vs. New York Mets',
      type: 'EVENT',
      subType: 'Basketball',
      date: '05-05-2020',
      venue: 'Staples Center, LA',
    },
    {
      resultID: 5,
      resultText: 'New York Knicks vs. Chicago Bulls',
      type: 'EVENT',
      subType: 'Basketball',
      date: '05-06-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 6,
      resultText: 'New York Giants vs. Green Bay Packers',
      type: 'EVENT',
      subType: 'Soccer',
      date: '05-07-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 6.5,
      resultText: 'New York Giants vs. Green Bay Packers',
      type: 'EVENT',
      subType: 'Soccer',
      date: '07-06-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 7,
      resultText: 'New York Yankees vs. New York Mets',
      type: 'EXPERIENCE',
      subType: 'Basketball',
      date: '08-06-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 8,
      resultText: 'New York Knicks vs. Chicago Bulls',
      type: 'EXPERIENCE',
      subType: 'Basketball',
      date: '05-06-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 9,
      resultText: 'New York Giants vs. Green Bay Packers',
      type: 'EXPERIENCE',
      subType: 'Soccer',
      date: '05-11-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 10,
      resultText: 'New York Giants vs. Green Bay Packers',
      type: 'EXPERIENCE',
      subType: 'Soccer',
      date: '11-06-2020',
      venue: 'Yankee Stadium, NY',
    },
    {
      resultID: 11,
      resultText: 'Madison Square Garden, NY',
      type: 'VENUE',
      subType: 'Venue',
      date: '',
      venue: '',
    },
    {
      resultID: 12,
      resultText: 'Barclays Center, NY',
      type: 'VENUE',
      subType: 'Venue',
      date: '',
      venue: '',
    },
    {
      resultID: 13,
      resultText: 'Yankee Stadium, NY',
      type: 'VENUE',
      subType: 'Venue',
      date: '',
      venue: '',
    },
    {
      resultID: 14,
      resultText: 'Staples Center, LA',
      type: 'VENUE',
      subType: 'Venue',
      date: '',
      venue: '',
    },
  ],
  errorCode: null,
  errorMessage: null,
};
